export const GET_WEATHER_INFO_START = 'GET_WEATHER_INFO_START'
export const GET_WEATHER_INFO_SUCCESS = 'GET_WEATHER_INFO_SUCCESS'
export const GET_WEATHER_INFO_FAILURE = 'GET_WEATHER_INFO_FAILURE'
export const CHANGE_DEGREE = 'CHANGE_DEGREE';
